# -*- coding: utf-8 -*-
"""歡迎使用 Colaboratory

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

score = input().split()
countF = 0
score_min, score_max = 100, 0
score_sum = 0

for s in score:
  if int(s) < 60: countF += 1   #Counting Fail
  sum += s  #Calculate Sum
  if s > max:
    max = s
  if s < min:
    min = s
avg = sum // len(score)

print(countF)
print(score_avg)
print(score_min, score_max)